version: 2.1

jobs:
  build-test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run:
          name: run tests
          command: PYTHONPATH=. pytest --maxfail=1 --disable-warnings -q
      - run: black --check app tests
      - run: coverage run -m pytest
      - run: coverage report

workflows:
  test-deploy:
    jobs:
      - build-test